### ISSUE TITLE
DirectX support with MinGW crashes.

### ISSUE THREAD

**Issue by martincohen** [martincohen/Punity#6]
Deeper investigation is needed to find out why MinGW crashes. Building with DirectX turned off should work. Backtrace here:

```
Program received signal SIGSEGV, Segmentation fault.
0x67f2b808 in d3d11!CreateDirect3D11SurfaceFromDXGISurface () from C:\Windows\SysWOW64\d3d11.dll
(gdb) backtrace
#0  0x67f2b808 in d3d11!CreateDirect3D11SurfaceFromDXGISurface () from C:\Windows\SysWOW64\d3d11.dll
#1  0x0041ee77 in punp_win32_d3d_render (buffer=0x2680000) at punity.c:1890
#2  0x0041fd60 in WinMain@16 (instance=0x400000, prev_instance=0x0, command_line=0x866430 "",
    show_code=10) at punity.c:2273
#3  0x00427c6b in main ()
```

**Comment by martincohen** [comment]
DirectX support is to be removed and replaced with OpenGL.
